version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./mysql_script.sql:/docker-entrypoint-initdb.d/1.sql"
  api_tech_challenge:
    build:
         context: .
         dockerfile: Dockerfile
    volumes:
      - .:/code
    enviroment:
      - MYSQL_DB=db
      - MYSQL_PASS=password
      - MYSQL_USER=root
      - MYSQL_HOST=localhost
    depends_on:
      - database

