apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: api_img
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"  # Minimum memory request
            cpu: "500m"      # Minimum CPU request
          limits:
            memory: "512Mi"  # Maximum memory limit
            cpu: "1"         # Maximum CPU limit

