
version: '3.3'

services: 
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    hostname: localhost #lembrar de mudar pra test
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./mysql_script.sql:/docker-entrypoint-initdb.d/1.sql"

